//
// Created by Дарья on 03.04.2021.
//

#ifndef MODELING_OF_TRANSPORT_NETWORKS_AUTOMATAGRIDVIEW_H
#define MODELING_OF_TRANSPORT_NETWORKS_AUTOMATAGRIDVIEW_H
#include <QWidget>

class AutomataView : QWidget {

};

#endif //MODELING_OF_TRANSPORT_NETWORKS_AUTOMATAGRIDVIEW_H
